### PR TITLE
feat: [multiformats pt 1] Removing Deprecated Package

### PR DESCRIPTION
**Pull request by whizzzkid**
In this PR:

- removing deprecated `peer-id` https://github.com/libp2p/js-peer-id/tree/master
- move to `@libp2p/peer-id` to support multiformats update

### CODE REVIEW

**Review by achingbrain — APPROVED** [review]
LGTM but CI is failing

**Comment by SgtPooki** [comment]
@whizzzkid the flakiness should have mostly been removed.. so it's not common that tests are flaky. Do you remember which test group failed?

**Comment by achingbrain** [comment]
@SgtPooki this is the failed build: https://github.com/ipfs/js-kubo-rpc-client/actions/runs/3865133823/attempts/1

**Comment by achingbrain** [comment]
Here's another one, same error but different platform: https://github.com/ipfs/js-kubo-rpc-client/actions/runs/3911896740/jobs/6685850228

**Comment by achingbrain** [comment]
TBH these tests have been flaky with kubo forever, it's probably a bug there.

**Comment by achingbrain** [comment]
Here's a different one failing: https://github.com/ipfs/js-kubo-rpc-client/actions/runs/3912285723/jobs/6686751096

**Pull request merged**
